language: node_js
node_js:
  - '0.12'
before_install:
  - npm install -g grunt-cli
  - npm install -g bower
install:
  - npm install
  - cd example && npm install && bower install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - grunt
  - cd example && grunt
  - cd example && grunt travis-protractor
